db/setup-mongo-connection #9
CoffeeShopTeam/CoffeeShop pull request #15
Opened 2023-06-10 15:26 UTC by roeezach

#9 
* add mongo connect configuration to the project
* install dotenv package and relay on that configuration.

2023-06-10 15:39 UTC, GilHeller requested changes

2023-06-10 15:39 UTC, GilHeller commented on index.js
> +const mongoConnect = require('./src/config/mongoConnect.js');
Consider using "index file pattern" (imports with `index.js` in every folder).

2023-06-10 15:39 UTC, GilHeller commented on package.json
> +    "run": "npm start"
Why have you added a script for `run`

2023-06-10 16:00 UTC, roeezach commented on package.json
> +    "run": "npm start"
to be able to use `npm start` easily instead if `npm start run`

2023-06-12 09:24 UTC, roeezach commented on index.js
> +const mongoConnect = require('./src/config/mongoConnect.js');
we would need to change the main `index.js` to another name and create index.js at the same level.
if I would use the `index.js` to import `mongoConnect` it would be the same length of import:
`./src/config/index.js`

2023-06-12 10:24 UTC, closed without merging